version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: db

  backend:
    build: .
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      - db
    container_name: backend

volumes:
  pgdata: