services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    command: python run.py
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata: