version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      sh -c "
        docker-entrypoint.sh postgres &
        sleep 10 &&
        psql -U $POSTGRES_USER -d $POSTGRES_DB -tc \"SELECT 1 FROM pg_database WHERE datname = 'test'\" | grep -q 1 ||
        psql -U $POSTGRES_USER -d $POSTGRES_DB -c 'CREATE DATABASE test;' &&
        wait
      "

  backend:
    build: .
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      - db
    container_name: backend

volumes:
  pgdata: